workflows:
  flutter-test:
    name: Flutter test workflow
    max_build_duration: 20
    labels:
      - Test
    environment:
      flutter: stable
      groups:
        - codecov_credentials
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
    triggering:
      branch_patterns:
        - include: true
          pattern: main
      events:
        - push
        - pull_request
      cancel_previous_builds: true
    when:
      changeset:
        includes:
          - lib/
          - test/
    scripts:
      - name: Exit test if keyword 'skiptestci' is defined
        script: |
          set -e
          set -x
          export COMMIT_MSG=$(git log -1 --pretty=%B)
          echo COMMIT_MSG
          if [[ $COMMIT_MSG == *"skiptestci"* ]]
            then
              echo "Commit includes 'skiptestci' in it's message, exiting..."
              exit 1
            else 
              echo "Commit message does not include 'skiptestci', moving forward..."
          fi
      - name: Get flutter packages
        script: flutter pub get
      - name: Run flutter analyze
        script: flutter analyze
      - name: Run flutter unit test
        script: |
          # HOMEBREW_NO_AUTO_UPDATE=1 brew install lcov
          # Install lcov if not already installed
          if ! command -v lcov &> /dev/null
            then echo "lcov is not installed. Installing..."
            HOMEBREW_NO_AUTO_UPDATE=1 brew install lcov
          else
            echo "lcov is already installed"
          fi
          
          # Run the tests and generate the coverage report
          # Redirect all output to test-results.json
          flutter test --coverage --machine > test-results.json
          
          # Check if any tests failed by searching for "-1" or negative digit in the test results
          if grep -qE '^-?[1-9]' test-results.json; 
            then echo "Some tests failed."
          exit 1
          fi
          
          # Extract the code coverage percentage
          code_coverage=$(lcov --list $CM_BUILD_DIR/coverage/lcov.info | sed -n "s/.*Total:|\(.*\)%.*/\1/p")
          
          # Print the code coverage percentage to the console
          echo "Code Coverage: ${code_coverage}% "
          
          # If the code coverage is less than the target, exit with an error
          if [ -z ${CODE_COVERAGE_TARGET+x} ];
            then echo "CODE_COVERAGE_TARGET is not defined."
          else
          if (( $(echo "$code_coverage < $CODE_COVERAGE_TARGET" | bc) ))
            then { echo "code coverage is less than expected" && exit 1; }
          fi
        test_report: test-results.json
      - name: Codecov upload
        script: |
          curl -Os https://uploader.codecov.io/latest/macos/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}